"""empty message

Revision ID: 2326c222c87b
Revises: f5ade591042f
Create Date: 2021-11-13 18:51:45.260700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2326c222c87b'
down_revision = 'f5ade591042f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoes', sa.Column('item_offer_info', sa.Boolean(), nullable=True))
    op.add_column('shoes', sa.Column('item_bid_info', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoes', 'item_bid_info')
    op.drop_column('shoes', 'item_offer_info')
    # ### end Alembic commands ###
