"""empty message

Revision ID: 2573b8fa044e
Revises: bedd7b48892d
Create Date: 2021-11-02 23:29:05.910224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2573b8fa044e'
down_revision = 'bedd7b48892d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoes', sa.Column('shoe_size', sa.Integer(), nullable=True))
    op.add_column('shoes', sa.Column('adult_shoe', sa.Boolean(), nullable=True))
    op.add_column('shoes', sa.Column('youth_shoe', sa.Boolean(), nullable=True))
    op.add_column('shoes', sa.Column('child_shoe', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoes', 'child_shoe')
    op.drop_column('shoes', 'youth_shoe')
    op.drop_column('shoes', 'adult_shoe')
    op.drop_column('shoes', 'shoe_size')
    # ### end Alembic commands ###
