"""empty message

Revision ID: df4a77cfc565
Revises: 2573b8fa044e
Create Date: 2021-11-06 14:39:09.320000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4a77cfc565'
down_revision = '2573b8fa044e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoes', sa.Column('sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoes', 'sold')
    # ### end Alembic commands ###
