"""empty message

Revision ID: f5ade591042f
Revises: df4a77cfc565
Create Date: 2021-11-10 21:52:56.326131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ade591042f'
down_revision = 'df4a77cfc565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoes', sa.Column('item_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoes', 'item_description')
    # ### end Alembic commands ###
